import { mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { tools } from '../src/tools.js';
const origin=(process.env.SITE_URL||'https://meow-pdf-merger-web.vercel.app').replace(/\/$/,'');
const paths={layers:'M4 7l8-4 8 4-8 4-8-4zm0 5l8 4 8-4M4 17l8 4 8-4',resize:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M8 8h8v8H8z',scissors:'M9 9l12 12M9 15L21 3M6 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm0 6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z',trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',rotate:'M3 9a9 9 0 1 1 0 7M3 3v6h6',image:'M3 3h18v18H3zM3 17l6-6 4 4 3-3 5 5M8 7h.01',book:'M12 5v16M12 5C8 2 4 3 2 4v15c4-1 7-1 10 2 3-3 6-3 10-2V4c-2-1-6-2-10 1',upload:'M12 16V3m-5 5l5-5 5 5M3 15v6h18v-6',shield:'M12 2l9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4zm-4 10l3 3 5-6',arrow:'M5 12h14m-5-5l5 5-5 5'};
const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.layers}"/></svg>`;
const cat=`<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M8 17V7l10 6h4L32 7v10c6 14-2 18-12 18S2 31 8 17Z" stroke="currentColor" stroke-width="2.3" stroke-linejoin="round"/><path d="M13 23h1m12 0h1m-9 4 2 2 2-2" stroke="currentColor" stroke-width="2.8" stroke-linecap="round"/></svg>`;
const footer=`<footer><a class="brand" href="/">${cat} MEOW <span>PDF</span></a><p>문서는 당신의 기기에. 시간은 당신의 일상에.</p><nav aria-label="사이트 안내"><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/disclaimer/">Disclaimer</a><a href="/guides/">사용 가이드</a><a href="/rss.xml">RSS ↗</a><a href="https://github.com/ANHOYA/MEOW-PDF-MERGER-WEB">GitHub ↗</a></nav><small>© 2026 MEOW PDF · Made with care by ANHOYA</small></footer>`;
function shell(title,description,path,body,active='') {
 const canonical=origin+path;
 const verify=[['google-site-verification',process.env.GOOGLE_SITE_VERIFICATION || (origin==='https://meow-pdf-merger-web.vercel.app'?'a_eWByDkzb8cI6L5RzHGvaakSZMnWO9Ss5at4s7g0BA':'')],['naver-site-verification',process.env.NAVER_SITE_VERIFICATION || (origin==='https://meow-pdf-merger-web.vercel.app'?'16061276fad381e8e6ba0199b845eb3aa9d8580c':'')],['msvalidate.01',process.env.BING_SITE_VERIFICATION || (origin==='https://meow-pdf-merger-web.vercel.app'?'B1A9AB3227804276568E8E93FB7D08A4':'')]].filter(([,v])=>v).map(([k,v])=>`<meta name="${k}" content="${v.replace(/[<>&"]/g,'')}">`).join('');
 return `<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | MEOW PDF</title><meta name="description" content="${description}"><meta name="theme-color" content="#f3f1f7"><link rel="canonical" href="${canonical}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="alternate" type="application/rss+xml" title="MEOW PDF 사용 가이드" href="/rss.xml"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="${title} | MEOW PDF"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${origin}/og-image.png"><meta name="twitter:card" content="summary_large_image">${verify}<link rel="stylesheet" href="/src/style.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebApplication',name:`MEOW PDF ${title}`,url:canonical,description,applicationCategory:'UtilitiesApplication',operatingSystem:'Web browser',inLanguage:'ko',offers:{'@type':'Offer',price:'0',priceCurrency:'KRW'}})}</script></head><body><a class="skip" href="#main">본문으로 건너뛰기</a><header class="site-header"><a class="brand" href="/">${cat} MEOW <span>PDF</span></a><nav aria-label="주 메뉴"><a href="/#tools" ${!active?'aria-current="page"':''}>모든 도구</a><a href="/guides/">사용 가이드</a><a href="/privacy/">프라이버시</a></nav><span class="header-pill"><i></i> 100% 무료 · 로컬 처리</span></header>${body}${footer}<script type="module" src="/src/main.js"></script></body></html>`;
}
const card=t=>`<a class="tool-card ${t.id==='merge'?'featured':''}" href="/tools/${t.id}/"><span class="tool-icon ${t.id}">${icon(t.icon)}</span>${t.badge?`<span class="badge">${t.badge}</span>`:''}<h3>${t.title}</h3><p>${t.short}</p><span class="card-arrow">↗</span></a>`;
const workspace=t=>`<section class="workspace glass" data-tool="${t.id}" aria-label="${t.title} 작업 공간"><div class="workspace-top"><span class="tool-icon ${t.id}">${icon(t.icon)}</span><div><h2>${t.title}</h2><p>${t.description}</p></div><span class="local-label">${icon('shield')} 기기 안에서만 처리</span></div><div class="workspace-body"><div class="dropzone" id="dropzone"><input id="files" type="file" ${['merge','resize','images','duplex'].includes(t.id)?'multiple':''} accept="${t.id==='images'?'.jpg,.jpeg,.png':'.pdf'}"><span class="upload-icon">${icon('upload')}</span><h3>파일을 여기에 놓아주세요</h3><p>${t.id==='images'?'JPG, PNG 이미지를 선택하세요':'PDF 파일을 선택하거나 끌어다 놓으세요'}</p><button class="primary" id="choose" type="button">${icon('plus')} 파일 선택하기 <span>＋</span></button><small>업로드 없이, 브라우저에서 안전하게</small></div><div id="file-list" aria-label="선택한 파일"></div><div class="options">${['extract','delete','rotate'].includes(t.id)?`<label>페이지 번호 <input id="pages" placeholder="${t.id==='rotate'?'비워두면 전체 페이지':'예: 1-3, 5'}" autocomplete="off"></label>`:''}${t.id==='rotate'?'<label>회전 방향<select id="angle"><option value="90">시계 방향 90°</option><option value="180">180°</option><option value="270">시계 반대 방향 90°</option></select></label>':''}${t.id==='resize'?'<label>용지 방향<select id="orientation"><option value="auto">원본 방향에 맞춰 자동</option><option value="portrait">A4 세로</option><option value="landscape">A4 가로</option></select></label><label>여백<select id="margin"><option value="0">없음 · 최대 크기</option><option value="28.3465">10 mm</option><option value="56.693">20 mm</option></select></label><p class="hint">비율을 유지해 A4에 맞춥니다. 링크·주석·편집 가능한 양식은 유지되지 않을 수 있습니다.</p>':''}${t.id==='duplex'?'<p class="hint">첫 번째 파일은 앞면, 두 번째 파일은 뒷면입니다. 화살표로 순서를 바꿀 수 있습니다.</p><label>뒷면 페이지 순서<select id="even-order"><option value="reverse">역순 (일반적인 단면 스캔)</option><option value="forward">정순</option></select></label><label class="check"><input type="checkbox" id="rotate-even"> 뒷면 180° 회전</label>':''}</div><p id="status" role="status" aria-live="polite"></p><div id="preview" class="preview" aria-label="처리 결과 미리보기"></div><div class="actions"><button id="clear" class="secondary" disabled>모두 지우기</button><button id="run" class="primary" disabled>${t.title} 실행 ${icon('arrow')}</button><a id="download" class="primary" hidden download>결과 다운로드 ↓</a></div><p class="hint">암호화 PDF는 지원하지 않습니다. 전자서명은 편집 후 유효하지 않을 수 있습니다. 원본을 보관하세요.</p></div></section>`;
const home=`<main id="main"><section class="hero"><div class="eyebrow"><span>작고 다정한 PDF 작업실</span><i>✦</i> PRIVATE BY DESIGN</div><h1>PDF 작업은 가볍게.<br>내 문서는 <em>안전하게.</em></h1><p>합치고, 정리하고, 딱 맞게 바꾸세요.<br>가입도, 결제도, 서버 업로드도 없는 나만의 PDF 도구.</p><div class="trust-row"><span>✓ 모든 기능 무료</span><span>✓ 파일 서버 전송 없음</span><span>✓ 설치 없이 바로</span></div><div class="hero-art" aria-hidden="true"><div class="orb"></div><div class="paper paper-back"><span>PDF</span><b></b><b></b><b></b></div><div class="paper paper-front">${cat}<span>less work,<br>more meow.</span><b></b><b></b><div class="paper-stamp">100%<small>YOURS</small></div></div><span class="floating-lock">${icon('shield')} 내 파일은 내 곁에</span><span class="spark">✧</span></div></section><section id="tools" class="tools-section"><div class="section-heading"><div><span class="eyebrow">YOUR EVERYDAY TOOLKIT</span><h2>오늘은 어떤 작업이 필요한가요?</h2></div><span>7가지 도구, 모두 무료</span></div><div class="tool-grid">${tools.map(card).join('')}</div></section>${workspace(tools[0])}<section class="promise"><div>${icon('shield')}<h2>내 문서가 떠나지 않는 작업실</h2><p>선택한 파일은 브라우저 메모리에서 처리됩니다.<br>파일을 저장하는 서버도, 회원가입도 없습니다.</p><a href="/privacy/">개인정보 보호 방식 알아보기 ↗</a></div><ol><li><span>01</span><div><h3>파일을 고르고</h3><p>내 기기의 PDF 또는 이미지를 선택하세요.</p></div></li><li><span>02</span><div><h3>원하는 대로 정리하고</h3><p>순서와 옵션을 정하고 실행하세요.</p></div></li><li><span>03</span><div><h3>바로 저장하세요</h3><p>완성된 파일을 내 기기로 다운로드하세요.</p></div></li></ol></section><section class="faq"><span class="eyebrow">A LITTLE HELP</span><h2>궁금한 점이 있나요?</h2><details><summary>정말 모든 기능이 무료인가요?</summary><p>네. 구독, 워터마크, 사용 횟수 과금 없이 제공됩니다. 처리 가능한 크기는 기기의 메모리와 브라우저 성능에 따라 달라집니다.</p></details><details><summary>파일은 어디에 저장되나요?</summary><p>선택한 파일과 결과는 현재 탭의 메모리에서 처리됩니다. 다운로드한 결과는 기기에 남으며, 모두 지우기 또는 탭 닫기로 앱의 파일 참조를 해제할 수 있습니다.</p></details><details><summary>A4로 바꾸면 내용이 잘리나요?</summary><p>가로세로 비율을 유지해 A4 안에 맞춥니다. 원본 비율에 따라 여백이 생길 수 있습니다.</p></details></section></main>`;
writeFileSync('index.html',shell('무료 PDF 도구 · 병합, A4 변환, 페이지 정리','서버 업로드 없이 브라우저에서 PDF 병합, A4 일괄 변환, 페이지 추출, 삭제, 회전과 양면 스캔 복원까지 무료로 이용하세요.','/',home));
const routes=['/'];
function page(path,title,description,body){mkdirSync('.'+path,{recursive:true});writeFileSync('.'+path+'index.html',shell(title,description,path,body,path));routes.push(path);}
for(const t of tools) page(`/tools/${t.id}/`,`${t.title} 무료 온라인 도구`,t.description,`<main id="main" class="tool-page"><a class="back" href="/#tools">← 모든 도구</a><div class="page-intro"><span class="eyebrow">LOCAL. FREE. YOURS.</span><h1>${t.title}</h1><p>${t.description}</p></div>${workspace(t)}<section class="related"><h2>다른 작업도 이어서 해보세요</h2><div class="tool-grid">${tools.filter(x=>x.id!==t.id).slice(0,3).map(card).join('')}</div></section></main>`);
const legal={privacy:['개인정보처리방침','파일은 내 기기에 머뭅니다.',`<h2>문서 처리</h2><p>MEOW PDF는 선택한 PDF와 이미지의 내용, 파일명, 처리 결과를 서버에 업로드하지 않습니다. 파일은 현재 브라우저 탭의 메모리에서 처리하며 앱은 문서를 원격 저장소나 브라우저 영구 저장소에 저장하지 않습니다. 다운로드한 파일과 원본은 사용자의 기기에 남습니다.</p><h2>접속 정보와 호스팅</h2><p>웹페이지와 프로그램 파일을 제공하는 호스팅 서비스(Vercel)는 서비스 운영과 보안을 위해 IP 주소, 요청 URL, 접속 시각, 브라우저 정보 등 접속 로그를 처리할 수 있습니다. 이는 PDF 내용의 업로드와 다릅니다. 보관 기간과 처리 방식은 호스팅 제공자의 정책에 따릅니다.</p><h2>쿠키 및 외부 서비스</h2><p>현재 앱에는 광고, 행동 분석, 추적 쿠키를 사용하지 않습니다. PDF 라이브러리와 글꼴은 외부 CDN에 의존하지 않습니다. GitHub 등 외부 링크를 방문하면 해당 서비스의 정책이 적용됩니다.</p><h2>메모리 해제</h2><p>모두 지우기 버튼을 누르거나 탭을 닫으면 앱의 파일 참조를 해제합니다. 실제 메모리 회수 시점은 브라우저가 관리합니다. 기기에 저장한 파일은 직접 삭제해야 합니다.</p><h2>문의와 변경</h2><p>운영자: ANHOYA. 문의는 <a href="https://github.com/ANHOYA/MEOW-PDF-MERGER-WEB/issues">GitHub Issues</a>로 접수합니다. 공개 문의에 개인 문서나 개인정보를 첨부하지 마세요. 서비스 변경 시 이 페이지의 시행일을 갱신합니다.</p>`],terms:['이용약관','무료로 사용하는 PDF 도구의 이용 안내.',`<h2>서비스</h2><p>MEOW PDF는 브라우저에서 실행하는 무료 문서 편집 도구입니다. 별도 회원가입과 유료 구독은 없습니다. 네트워크, 브라우저, 기기 환경에 따라 사용이 제한될 수 있습니다.</p><h2>사용자의 책임</h2><p>처리할 권한이 있는 문서만 사용하세요. 문서의 저작권과 사용 권리는 원 권리자에게 있으며 운영자는 업로드나 권리 양도를 요구하지 않습니다. 결과를 확인하고 원본을 별도로 보관하세요.</p><h2>서비스 변경</h2><p>기능은 개선되거나 중단될 수 있습니다. 지속 제공이나 특정 목적 적합성을 보장하지 않습니다. 적용 법령이 보장하는 이용자의 권리를 제한하지 않습니다.</p><h2>문의</h2><p><a href="https://github.com/ANHOYA/MEOW-PDF-MERGER-WEB/issues">프로젝트 이슈</a>를 통해 오류와 개선 의견을 알려주세요.</p>`],disclaimer:['면책 안내','결과를 확인하고 원본은 보관하세요.',`<h2>처리 결과</h2><p>PDF 구조와 글꼴, 주석, 양식, 암호화 여부에 따라 결과가 달라질 수 있습니다. 중요한 문서는 저장 후 페이지 수, 순서, 방향과 내용을 확인하세요.</p><h2>기능의 범위</h2><p>암호가 걸린 PDF의 암호 해제, OCR, 문서 진위 검증은 제공하지 않습니다. A4 변환에서는 링크와 주석, 편집 가능한 양식이 유지되지 않을 수 있습니다. PDF 편집은 전자서명의 유효성을 변경할 수 있습니다.</p><h2>가용성과 책임</h2><p>기기 메모리가 부족하면 작업이 실패할 수 있습니다. 서비스는 있는 그대로 제공되며 오류 없는 처리나 데이터 복구를 보장하지 않습니다. 법령상 배제할 수 없는 책임까지 면제한다는 의미는 아닙니다.</p>`]};
for(const [key,[title,desc,body]] of Object.entries(legal)) page(`/${key}/`,title,desc,`<main id="main" class="document glass"><span class="eyebrow">MEOW PDF · ${key.toUpperCase()}</span><h1>${title}</h1><p class="lead">${desc}</p><p>시행일: 2026년 9월 30일</p>${body}</main>`);
const articles=[['merge-pdf','PDF를 원하는 순서로 합치는 방법','PDF 병합 도구에서 파일을 선택하세요. 목록의 위·아래 화살표로 파일 순서를 바꾼 뒤 실행합니다. 각 문서의 페이지는 원래 순서로 이어집니다. 결과 미리보기를 확인하고 다운로드하세요.','merge'],['resize-a4','PDF 여러 개를 A4로 일괄 변환하는 방법','A4 일괄 변환에서 PDF를 여러 개 선택하세요. 자동 방향 또는 세로·가로 방향과 여백을 지정합니다. 원본의 비율을 유지해 A4 안에 맞추므로 내용이 잘리지 않습니다. 여러 파일의 결과는 ZIP으로 다운로드합니다. 링크·주석·양식 보존이 필요하면 원본을 유지하세요.','resize'],['duplex-scan','단면 스캐너로 양면 문서를 복원하는 방법','앞면만 스캔한 PDF를 먼저, 뒷면만 스캔한 PDF를 두 번째로 선택하세요. 일반적인 ADF 스캔에서는 뒷면이 역순이므로 기본 옵션을 사용합니다. 스캐너에 따라 정순 또는 뒷면 180도 회전을 선택하세요. 앞면이 한 페이지 더 많은 문서도 지원합니다. 결과 순서를 확인하고 저장하세요.','duplex']];
page('/guides/','PDF 사용 가이드','병합, A4 변환, 양면 스캔 복원을 단계별로 알아보세요.',`<main id="main" class="document glass"><span class="eyebrow">SMALL GUIDES, BIG HELP</span><h1>PDF, 조금 더 쉽게.</h1>${articles.map(([id,title,body])=>`<article><h2><a href="/guides/${id}/">${title} ↗</a></h2><p>${body}</p></article>`).join('')}</main>`);
for(const [id,title,body,tool] of articles)page(`/guides/${id}/`,title,title,`<main id="main" class="document glass"><a href="/guides/">← 사용 가이드</a><h1>${title}</h1><p>${body}</p><a class="primary" href="/tools/${tool}/">도구 열기 →</a></main>`);
const xml=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
writeFileSync('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(path=>`<url><loc>${origin}${path}</loc></url>`).join('')}</urlset>`);
writeFileSync('public/rss.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>MEOW PDF 사용 가이드</title><link>${origin}/guides/</link><description>내 기기에서 안전하게 PDF 작업하기</description><language>ko</language>${articles.map(([id,title,body])=>`<item><title>${title}</title><link>${origin}/guides/${id}/</link><guid>${origin}/guides/${id}/</guid><description>${xml(body)}</description><pubDate>Wed, 30 Sep 2026 00:00:00 GMT</pubDate></item>`).join('')}</channel></rss>`);
writeFileSync('public/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
writeFileSync('public/favicon.svg',cat.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" ').replaceAll('currentColor','#7461b5'));
writeFileSync('public/404.html',shell('페이지를 찾을 수 없습니다','다른 PDF 도구를 찾아보세요.','/404.html','<main id="main" class="document glass"><h1>길을 잃으셨나요?</h1><p>이 페이지는 존재하지 않습니다.</p><a href="/">PDF 작업실로 돌아가기 →</a></main>').replace('<head>','<head><meta name="robots" content="noindex">').replace('<script type="module" src="/src/main.js"></script>','').replace('/src/style.css','/404.css'));

copyFileSync('src/style.css','public/404.css');
